### ISSUE TITLE
Dispatch Needs

### ISSUE THREAD

**Issue by modernsnipe14** [braukStauter/FLRPServ#3]
- Edit live map to have FLRP name on tab and display in game blips

- If possible a way for dispatch to see police/F&R calls

**Comment by modernsnipe14** [comment]
Is there a way to delete incidents such as tests or training incidents so that weekly reports can reflect accurately.

**Comment by braukStauter** [comment]
The live-map on the box is only temporary and will be moved to the actual website so that won't be changed on the box.

All users on the CAD can see all calls. There is no permission system for call viewing. 

Currently there is no way to delete incidents. This is a safeguard and so we always have an accurate representation of incidents, however, I have added a incident type 'Training' that will help distinguish between what's training and what's not.
